Repository elo7/tech-blog, pull requests merged in 2018-11, with the labels that each got.

#212 [fix-card] Corrige layout da página do autor
  src/assets/posts.css.scss
  src/assets/publisher.css.scss
  src/layouts/publisher.html.hb
Labels: # APPROVED ♥‿♥, - HackDay, BUG FIX (ﾉ◕ヮ◕)ﾉ, Martell

#213 Capas para os posts do Sr. Saúde (eu)
  src/assets/images/cover/javascript-e-a11y-capa.jpg
  src/assets/images/cover/progressive-web-apps.jpg
  src/assets/images/cover/testando-acessibilidade-cover.jpg
  src/assets/images/cover/um-pouco-sobre-css-js-a11y-cover.png
  src/assets/images/javascript-e-a11y-capa.jpg
  src/posts/a-tecnologia-por-tras-de-progressive-web-apps.html.md
  src/posts/javascript-e-a11y.html.md
  src/posts/testando-acessibilidade.html.md
  src/posts/um-pouco-sobre-css-js-a11y.html.md
Labels: # APPROVED ♥‿♥, - HackDay, ENHANCEMENT (•̀o•́)ง

#215 [cover-ljtfreitas] Cover images
  src/assets/images/cover/microservicos-e-rest.png
  src/assets/images/cover/novidades-do-junit-5-parte-1.png
  src/assets/images/cover/novidades-do-junit-5-parte-2.png
  src/assets/images/cover/programacao-reativa-parte-2.png
  src/assets/images/cover/programacao-reativa-parte-3.png
  src/assets/images/cover/programacao-reativa.png
  src/assets/images/cover/testes-de-codigo-com-mockito-parte-2.png
  src/assets/images/cover/testes-de-codigo-com-mockito.png
  src/posts/microservicos-rest.html.md
  src/posts/novidades-do-junit-5-parte-1.html.md
  src/posts/novidades-do-junit-5-parte-2.html.md
  src/posts/programacao-reativa-parte-2.html.md
  src/posts/programacao-reativa-parte-3.html.md
  src/posts/programacao-reativa.html.md
  src/posts/testes-codigo-mockito-2.html.md
  src/posts/testes-codigo-mockito.html.md
Labels: # APPROVED ♥‿♥, ENHANCEMENT (•̀o•́)ง
