Repository elo7/tech-blog, pull requests merged in 2019-03, with the labels that each got.

#217 [POST] Intersection observer
  src/assets/images/cover/intersection-observer.png
  src/assets/images/intersection-observer-carrossel.gif
  src/assets/images/intersection-observer-page-2.png
  src/assets/images/intersection-observer-page.png
  src/posts/intersection-observer.html.md
Labels: # APPROVED PORTUGUÊS, # APPROVED TECH, # APPROVED ♥‿♥, - HackDay, Martell, POST (⌐■_■)

#224 [fix-fernanda] Atualiza rede social
  src/publishers/fernandabernardo.html.md
Labels: # APPROVED ♥‿♥, - HackDay, Martell

#226 Adiciona google search console
  src/layouts/page.html.hb
Labels: - HackDay
