Repository elo7/tech-blog, pull requests merged in 2019-06, with the labels that each got.

#248 [POST] Front-End - Coisas de que nós nos orgulhamos em 2018!
  content/images/cover/retrospectiva-2018.jpg
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-1.gif
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-2.png
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-3.png
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-4.png
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-5.png
  content/images/front-end-coisas-que-nos-nos-orgulhamos-em-2018-6.png
  content/posts/front-end-coisas-que-nos-nos-orgulhamos-em-2018.md
Labels: # APPROVED PORTUGUÊS, # APPROVED TECH, # APPROVED ♥‿♥, - HackDay, Martell, POST (⌐■_■)

#256 [meetups-elo7] Adiciona página de meetups
  content/images/ico/calendar.png
  content/meetups/backendbr.md
  content/meetups/docker.md
  content/meetups/golang.md
  content/meetups/jssp.md
  content/meetups/kubernetes.md
  content/meetups/nerdzao.md
  content/meetups/nodebr.md
  content/meetups/soujava.md
  layouts/partials/header.html
  layouts/section/meetups.html
  static/css/meetups.scss
Labels: # APPROVED ♥‿♥, - HackDay, ENHANCEMENT (•̀o•́)ง, Martell

#223 [POST] Reinforcement Learning Parte 1
  content/authors/onimaru.md
  content/images/cover/reinforcement-learning-parte-1.png
  content/images/reinforcement-learning-parte-1-introducao-1.png
  content/images/reinforcement-learning-parte-1-introducao-2.png
  content/images/reinforcement-learning-parte-1-introducao-3.png
  content/images/reinforcement-learning-parte-1-introducao-4.png
  content/posts/reinforcement-learning-parte-1.md
Labels: # APPROVED PORTUGUÊS, - HackDay, Hightower, POST (⌐■_■)

#257 [fix-analytics] Fix para enviar dados para GA
  layouts/authors/single.html
  layouts/category/category.html
  layouts/posts/single.html
  layouts/section/meetups.html
  layouts/section/talks.html
  layouts/tag/tag.html
  layouts/talks/single.html
Labels: # APPROVED ♥‿♥, - HackDay, BUG FIX (ﾉ◕ヮ◕)ﾉ, Martell

#260 Adiciona page_type para busca
  layouts/authors/single.html
  layouts/category/category.html
  layouts/posts/single.html
  layouts/tag/tag.html
  layouts/talks/single.html
Labels: # APPROVED ♥‿♥
